# Generated by Django 6.0.7 on 2026-07-08 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("category", models.CharField(max_length=80)),
                ("priority", models.CharField(default="높음", max_length=30)),
                ("status", models.CharField(default="진행 필요", max_length=40)),
                ("output", models.TextField(blank=True)),
                ("risk", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="MemberSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_name", models.CharField(max_length=80)),
                ("trainer_name", models.CharField(default="김라이트", max_length=80)),
                ("goal", models.CharField(max_length=120)),
                ("discomfort_area", models.CharField(blank=True, max_length=120)),
                ("qs_score", models.FloatField(default=0)),
                ("jatc_score", models.FloatField(default=0)),
                ("form_accuracy", models.FloatField(default=0)),
                ("pain_response", models.FloatField(default=0)),
                ("rpe", models.FloatField(default=0)),
                ("qc_score", models.FloatField(default=100)),
                ("qs_form_component", models.FloatField(default=0)),
                ("qs_discomfort_component", models.FloatField(default=0)),
                ("qs_rpe_component", models.FloatField(default=0)),
                ("qs_qc_component", models.FloatField(default=100)),
                (
                    "safety_notice",
                    models.CharField(
                        default="비의료 운동상담 참고, 트레이너 검토 필요",
                        max_length=80,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("AUTO", "AUTO"),
                            ("REVIEW", "REVIEW"),
                            ("BLOCK", "BLOCK"),
                        ],
                        default="AUTO",
                        max_length=10,
                    ),
                ),
                (
                    "qc_status",
                    models.CharField(
                        choices=[
                            ("PASS", "PASS"),
                            ("CHECK", "CHECK"),
                            ("FAIL", "FAIL"),
                        ],
                        default="PASS",
                        max_length=10,
                    ),
                ),
                ("memo", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="accounts.memberprofile",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_sessions",
                        to="accounts.trainerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-qs_score"],
            },
        ),
    ]
