# Generated by Django 6.0.6 on 2026-07-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0002_membersession_member_membersession_trainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersession",
            name="qc_score",
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name="membersession",
            name="qs_discomfort_component",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="membersession",
            name="qs_form_component",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="membersession",
            name="qs_qc_component",
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name="membersession",
            name="qs_rpe_component",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="membersession",
            name="safety_notice",
            field=models.CharField(
                default="비의료 운동상담 참고, 트레이너 검토 필요", max_length=80
            ),
        ),
    ]
