# Generated by Django 6.0.6 on 2026-07-06 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0002_membersession_member_membersession_trainer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synthetic_id", models.CharField(max_length=40, unique=True)),
                ("display_label", models.CharField(max_length=80)),
                ("goal", models.CharField(blank=True, max_length=120)),
                ("experience_level", models.CharField(blank=True, max_length=40)),
                ("discomfort_area", models.CharField(blank=True, max_length=80)),
                (
                    "consent_status",
                    models.CharField(default="synthetic_demo", max_length=30),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["synthetic_id"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=40, unique=True)),
                ("exercise_name", models.CharField(max_length=120)),
                ("session_date", models.DateField()),
                ("planned_reps", models.PositiveIntegerField(default=0)),
                ("completed_reps", models.PositiveIntegerField(default=0)),
                ("planned_rest_seconds", models.PositiveIntegerField(default=0)),
                ("actual_rest_seconds", models.PositiveIntegerField(default=0)),
                ("rpe", models.PositiveSmallIntegerField(default=0)),
                ("pain_response", models.PositiveSmallIntegerField(default=0)),
                ("trainer_memo", models.TextField(blank=True)),
                ("capture_condition", models.CharField(blank=True, max_length=120)),
                (
                    "qc_status",
                    models.CharField(
                        choices=[
                            ("PASS", "PASS"),
                            ("CHECK", "CHECK"),
                            ("FAIL", "FAIL"),
                        ],
                        default="PASS",
                        max_length=10,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("AUTO", "AUTO"),
                            ("REVIEW", "REVIEW"),
                            ("BLOCK", "BLOCK"),
                        ],
                        default="AUTO",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_records",
                        to="lightone.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-session_date", "session_id"],
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posture_score", models.FloatField(default=0)),
                ("lifestyle_score", models.FloatField(default=0)),
                ("rep_achievement_rate", models.FloatField(default=0)),
                ("rest_compliance", models.FloatField(default=0)),
                ("pain_score", models.FloatField(default=0)),
                ("function_training_score", models.FloatField(default=0)),
                ("qs_score", models.FloatField(default=0)),
                ("jatc_score", models.FloatField(default=0)),
                (
                    "review_signal",
                    models.CharField(
                        choices=[
                            ("AUTO", "AUTO"),
                            ("REVIEW", "REVIEW"),
                            ("BLOCK", "BLOCK"),
                        ],
                        default="AUTO",
                        max_length=10,
                    ),
                ),
                ("counseling_priority", models.PositiveSmallIntegerField(default=3)),
                (
                    "report_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("READY", "Ready"),
                            ("HELD", "Held"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("review_note", models.TextField(blank=True)),
                ("trainer_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator",
                        to="lightone.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-qs_score", "session__session_id"],
            },
        ),
    ]
