# Generated by Django 6.0.6 on 2026-07-06 22:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0002_membersession_member_membersession_trainer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "member_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("Other", "Other")],
                        help_text="비의료 참고 목적의 성별 분류이며 직접 식별정보를 포함하지 않습니다.",
                        max_length=10,
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        help_text="비의료 참고 목적의 연령대입니다.", max_length=20
                    ),
                ),
                (
                    "goals",
                    models.TextField(
                        blank=True, help_text="비의료 참고 목적의 운동 목표입니다."
                    ),
                ),
                (
                    "consent",
                    models.BooleanField(
                        default=False,
                        help_text="비의료 참고 데이터 활용 동의 여부입니다.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "ordering": ["age_group", "member_id"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        help_text="비의료 참고 목적의 운동 세션 일시입니다."
                    ),
                ),
                (
                    "exercise_name",
                    models.CharField(
                        help_text="비의료 참고 목적의 운동명입니다.", max_length=120
                    ),
                ),
                (
                    "sets",
                    models.PositiveIntegerField(
                        help_text="비의료 참고 목적의 세트 수입니다."
                    ),
                ),
                (
                    "reps_target",
                    models.PositiveIntegerField(
                        help_text="비의료 참고 목적의 목표 반복 수입니다."
                    ),
                ),
                (
                    "reps_completed",
                    models.PositiveIntegerField(
                        help_text="비의료 참고 목적의 완료 반복 수입니다."
                    ),
                ),
                (
                    "rpe",
                    models.FloatField(help_text="비의료 참고 목적의 운동자각도입니다."),
                ),
                (
                    "pain_response",
                    models.PositiveSmallIntegerField(
                        help_text="비의료 참고 목적의 통증 반응 점수입니다."
                    ),
                ),
                (
                    "trainer_notes",
                    models.TextField(
                        blank=True, help_text="비의료 참고 목적의 트레이너 메모입니다."
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="lightone.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "ordering": ["-date", "exercise_name", "session_id"],
            },
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "indicator_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qs_score",
                    models.FloatField(help_text="비의료 참고 목적의 품질 점수입니다."),
                ),
                (
                    "form_accuracy",
                    models.FloatField(
                        help_text="비의료 참고 목적의 자세 정확도입니다."
                    ),
                ),
                (
                    "rep_rate",
                    models.FloatField(help_text="비의료 참고 목적의 반복 속도입니다."),
                ),
                (
                    "rest_compliance",
                    models.FloatField(
                        help_text="비의료 참고 목적의 휴식 준수율입니다."
                    ),
                ),
                (
                    "pain_score",
                    models.FloatField(help_text="비의료 참고 목적의 통증 점수입니다."),
                ),
                (
                    "jatc_pain",
                    models.FloatField(
                        help_text="비의료 참고 목적의 JATC 통증 지표입니다."
                    ),
                ),
                (
                    "jatc_posture",
                    models.FloatField(
                        help_text="비의료 참고 목적의 JATC 자세 지표입니다."
                    ),
                ),
                (
                    "jatc_function",
                    models.FloatField(
                        help_text="비의료 참고 목적의 JATC 기능 지표입니다."
                    ),
                ),
                (
                    "jatc_lifestyle",
                    models.FloatField(
                        help_text="비의료 참고 목적의 JATC 생활습관 지표입니다."
                    ),
                ),
                (
                    "routing_status",
                    models.CharField(
                        choices=[
                            ("AUTO", "AUTO"),
                            ("REVIEW", "REVIEW"),
                            ("BLOCK", "BLOCK"),
                        ],
                        default="AUTO",
                        help_text="비의료 참고 목적의 자동 라우팅 상태입니다.",
                        max_length=10,
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator",
                        to="lightone.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicator",
                "verbose_name_plural": "Indicators",
                "ordering": ["routing_status", "indicator_id"],
            },
        ),
    ]
