# Generated by Django 6.0.6 on 2026-07-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0003_member_session_indicator"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersession",
            name="function_training_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="membersession",
            name="lifestyle_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="membersession",
            name="posture_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="membersession",
            name="review_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="membersession",
            name="safety_notice",
            field=models.TextField(default="비의료 운동상담 참고, 트레이너 검토 필요"),
        ),
        migrations.AddField(
            model_name="membersession",
            name="trainer_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
