# Generated by Django 6.0.6 on 2026-07-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0003_member_session_indicator"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersession",
            name="function_training_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="membersession",
            name="lifestyle_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="membersession",
            name="posture_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="membersession",
            name="qc_score",
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name="membersession",
            name="review_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="membersession",
            name="safety_notice",
            field=models.TextField(
                default="LIGHT ONE은 비의료 운동상담 보조 도구입니다. QS/JATC와 AUTO/REVIEW/BLOCK은 PT 상담 참고 신호이며, REVIEW/BLOCK은 트레이너가 안전 신호를 확인한 뒤 진행 여부를 안내합니다."
            ),
        ),
        migrations.AddField(
            model_name="membersession",
            name="trainer_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
