# Generated by Codex on 2026-07-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightone', '0004_membersession_function_training_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='lightone.session'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='member_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='lightone.membersession'),
        ),
    ]
