# Generated by Django 6.0.6 on 2026-07-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0004_membersession_function_training_score_and_more"),
    ]

    operations = []
