# Generated by Codex on 2026-07-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0004_membersession_function_training_score_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Indicator",
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qs_score", models.FloatField(default=0)),
                ("jatc_score", models.FloatField(default=0)),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("AUTO", "AUTO"),
                            ("REVIEW", "REVIEW"),
                            ("BLOCK", "BLOCK"),
                        ],
                        default="AUTO",
                        max_length=10,
                    ),
                ),
                (
                    "qc_status",
                    models.CharField(
                        choices=[
                            ("PASS", "PASS"),
                            ("CHECK", "CHECK"),
                            ("FAIL", "FAIL"),
                        ],
                        default="PASS",
                        max_length=10,
                    ),
                ),
                (
                    "non_medical_notice",
                    models.TextField(
                        default="LIGHT ONE은 비의료 운동상담 보조 도구입니다. QS/JATC와 AUTO/REVIEW/BLOCK은 진단·치료·처방이 아니며, 통증이나 이상 반응이 있으면 운동을 중단하고 전문가 상담을 권고합니다."
                    ),
                ),
                ("trainer_review_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator",
                        to="lightone.membersession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-qs_score"],
            },
        ),
    ]
