# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0004_membersession_function_training_score_and_more"),
        ("lightone", "0003_membersession_qc_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersession",
            name="rep_score",
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name="membersession",
            name="rest_score",
            field=models.FloatField(default=100),
        ),
    ]
