# Generated by Codex on 2026-07-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightone', '0004_membersession_function_training_score_and_more'),
    ]

    operations = []
