# Generated by Django 6.0.6 on 2026-07-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0004_membersession_function_training_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="jatc_score",
            field=models.FloatField(
                default=0, help_text="비의료 운동상담 참고용 JATC 점수입니다."
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="review_note",
            field=models.TextField(
                blank=True, help_text="비의료 운동상담 참고용 안내 문구입니다."
            ),
        ),
        migrations.AlterField(
            model_name="membersession",
            name="jatc_score",
            field=models.FloatField(
                default=0, help_text="비의료 운동상담 참고용 JATC 점수입니다."
            ),
        ),
        migrations.AlterField(
            model_name="membersession",
            name="safety_notice",
            field=models.TextField(default="비의료 운동상담 참고, 트레이너 검토 필요"),
        ),
    ]
