# Generated by Django 6.0.6 on 2026-07-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0005_replace_indicator_with_membersession_indicator"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="non_medical_notice",
            field=models.TextField(default="비의료 운동상담 참고, 트레이너 검토 필요"),
        ),
        migrations.AlterField(
            model_name="membersession",
            name="safety_notice",
            field=models.TextField(default="비의료 운동상담 참고, 트레이너 검토 필요"),
        ),
    ]
