# Generated by Codex on 2026-07-06

from django.db import migrations, models

import lightone.algorithms


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0005_membersession_rep_rest_scores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membersession",
            name="safety_notice",
            field=models.TextField(default=lightone.algorithms.SAFETY_NOTICE),
        ),
    ]
