# Generated by Django 6.0.7 on 2026-07-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0005_alter_indicator_jatc_score_and_more"),
        ("lightone", "0005_membersession_indicator_link"),
        ("lightone", "0006_alter_membersession_safety_notice"),
        ("lightone", "0006_membersession_updated_at_and_more"),
    ]

    operations = []
