# Generated by Django 6.0.7 on 2026-07-10 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0007_merge_20260710_1947"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="counseling_priority",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="indicator",
            name="function_training_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="indicator",
            name="lifestyle_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="indicator",
            name="pain_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="indicator",
            name="posture_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="indicator",
            name="rep_achievement_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="indicator",
            name="report_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("READY", "Ready"),
                    ("HELD", "Held"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="rest_compliance",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="indicator",
            name="review_signal",
            field=models.CharField(
                choices=[
                    ("AUTO", "AUTO"),
                    ("REVIEW", "REVIEW"),
                    ("BLOCK", "BLOCK"),
                ],
                default="AUTO",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="trainer_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="age_group",
            field=models.CharField(
                blank=True, help_text="비의료 참고 목적의 연령대입니다.", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="consent",
            field=models.BooleanField(
                default=False, help_text="비의료 참고 데이터 활용 동의 여부입니다."
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("Other", "Other")],
                help_text="비의료 참고 목적의 성별 분류입니다.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="goals",
            field=models.TextField(
                blank=True, help_text="비의료 참고 목적의 운동 목표입니다."
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="member_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="jatc_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="indicator",
            name="review_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="display_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="member",
            name="synthetic_id",
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
