# Generated by Django 6.0.7 on 2026-07-10 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightone", "0008_indicator_counseling_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicator",
                to="lightone.session",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="member_session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicator",
                to="lightone.membersession",
            ),
        ),
    ]
