# Generated by Django 6.0.6 on 2026-06-30 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('lightone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersession',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.memberprofile'),
        ),
        migrations.AddField(
            model_name='membersession',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_sessions', to='accounts.trainerprofile'),
        ),
    ]
